#!/bin/sh
if [ ! -n "$1" ] ; then
  echo "Usage: $0 <hexaddr> [<length> [<unitsize>]]: Dump a memory region as words"
else
  if [ ! -n "$2" ] ; then
    LEN=1
  else
    LEN=$2
  fi
echo m $1 $LEN w > /proc/bcmlog
fi
